MONGODB_HOST: mongodb-{{ env }}.dso86s.xyz # mongodb-dev.dso86s.xyz
REDIS_HOST: redis-{{ env }}.dso86s.xyz
CATALOGUE_HOST: catalogue-{{ env }}.dso86s.xyz
CART_HOST: cart-{{ env }}.dso86s.xyz
USER_HOST: user-{{ env }}.dso86s.xyz
MYSQL_HOST: mysql-{{ env }}.dso86s.xyz
RABBITMQ_HOST: rabbitmq-{{ env }}.dso86s.xyz
SHIPPING_HOST: shipping-{{ env }}.dso86s.xyz
PAYMENT_HOST: payment-{{ env }}.dso86s.xyz
